# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c025d8f3601bf0275036582bfe7a163d41b0c5ace3799360477861009ced13108aeb86372702338238c66c3ae5ec7d0a5727264cb2ec75234dc1c20002ddf190

test:
  secret_key_base: 0c46a983c21b433410686292981630533aafc20c7657baa620284e0b614b0a3ade42bc8cc640774b6a7ba6f736639364a1abeab4fc40c25062b03dfd5667ff04

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
